name: Update JSON Data

on:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/**'
  workflow_dispatch:  # allows manual trigger

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Run Notes JSON Generator
        run: python generate_notes_json.py
        working-directory: scripts/


      # - name: Run Certificates JSON Generator
      #   run: python generate_certificates_json.py
      #   working-directory: scripts/

      - name: Run Writeups JSON Generator
        run: python generate_writeup_json.py
        working-directory: scripts/

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update JSON files [auto]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

